[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["web", "router", "launch"] }
ui = { workspace = true }
api = { workspace = true }

[features]
default = []
web = ["dioxus/web"]
server = ["dioxus/server"]
